[terminal]
shell = { program = "pwsh" }

[font]
size = 12

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 3, y = 3 }
